apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    labels:
      template: generic-java-jenkins-pipeline
    name: tekton
    namespace: basic-spring-boot-build
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    labels:
      template: generic-java-jenkins-pipeline
    name: tekton_edit
    namespace: basic-spring-boot-build
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: edit
  subjects:
  - kind: ServiceAccount
    name: tekton
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      application: basic-spring-boot
      template: generic-java-jenkins-pipeline
    name: basic-spring-boot
    namespace: basic-spring-boot-build
- apiVersion: tekton.dev/v1alpha1
  kind: PipelineResource
  metadata:
    labels:
      template: generic-java-jenkins-pipeline
    name: basic-spring-boot-image
    namespace: basic-spring-boot-build
  spec:
    params:
    - name: url
      value: image-registry.openshift-image-registry.svc:5000/basic-spring-boot-build/basic-spring-boot
    type: image
- apiVersion: tekton.dev/v1alpha1
  kind: PipelineResource
  metadata:
    labels:
      template: generic-java-jenkins-pipeline
    name: basic-spring-boot-git
    namespace: basic-spring-boot-build
  spec:
    params:
    - name: url
      value: https://github.com/ably77/spring-rest.git
    - name: revision
      value: master
    type: git
- apiVersion: tekton.dev/v1alpha1
  kind: Task
  metadata:
    labels:
      template: generic-java-jenkins-pipeline
    name: maven-build-binary-build
    namespace: basic-spring-boot-build
  spec:
    inputs:
      resources:
      - name: source
        type: git
    steps:
    - args:
      - package
      command:
      - /usr/bin/mvn
      image: maven:3.6.0-jdk-8-slim
      name: package
      workingDir: /workspace/source
    - args:
      - -p
      - /workspace/source/upload
      command:
      - mkdir
      image: quay.io/openshift-pipeline/openshift-cli:latest
      name: make-upload-dir
    - args:
      - /workspace/source/target/shift-rest-1.0.0-SNAPSHOT.jar
      - /workspace/source/upload
      command:
      - cp
      image: quay.io/openshift-pipeline/openshift-cli:latest
      name: copy-assets
    - args:
      - start-build
      - -w
      - -F
      - basic-spring-boot
      - --from-dir
      - .
      command:
      - /usr/local/bin/oc
      image: quay.io/openshift-pipeline/openshift-cli:latest
      name: oc-binary-build
      workingDir: /workspace/source/upload
- apiVersion: tekton.dev/v1alpha1
  kind: Pipeline
  metadata:
    labels:
      template: generic-java-jenkins-pipeline
    name: basic-spring-boot-pipeline
    namespace: basic-spring-boot-build
  spec:
    resources:
    - name: basic-spring-boot-git
      type: git
    tasks:
    - name: maven-build-binary-build
      resources:
        inputs:
        - name: source
          resource: basic-spring-boot-git
      taskRef:
        name: maven-build-binary-build
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      argocd.argoproj.io/sync-options: Validate=false
    labels:
      application: basic-spring-boot
      template: generic-java-jenkins-pipeline
    name: basic-spring-boot
    namespace: basic-spring-boot-build
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: basic-spring-boot:latest
    source:
      binary: {}
      type: Binary
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: redhat-openjdk18-openshift:1.1
          namespace: openshift
      type: Source
kind: List
metadata: {}
